service: ceu-email-trigger

provider:
  name: aws  
  runtime: dotnet6
  region: us-east-1
  stage: ${opt:stage,'dev'}

  iam:
    role: arn:aws:iam::080412924906:role/SES-Basic-Sending

    
package:
  artifact: bin/release/net6.0/deploy-package.zip

functions:
  main:
    handler: GRVAS.Training.CeuEmailTrigger::GRVAS.Training.CeuEmailTrigger.Function::FunctionHandler
    timeout: 600
    events:
      - eventBridge:
          schedule: cron(0 14 1 * ? *)